codequality:
  tags:
    - docker
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker info
    - docker pull acdha/flake8-codeclimate
  script:
    - docker run --rm --volume "$PWD":/code acdha/flake8-codeclimate /code > codeclimate.json || true
  artifacts:
    paths: [codeclimate.json]
