exclude: ".*/vendor/.*"
repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 22.1.0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: check-added-large-files
            args: ["--maxkb=256"]
          - id: check-ast
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-xml
          - id: check-yaml
          - id: debug-statements
          - id: detect-aws-credentials
            args: ["--allow-missing-credentials"]
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: ["--fix=lf"]
          - id: pretty-format-json
            args: ["--autofix", "--no-sort-keys", "--indent=4"]
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.5.1
      hooks:
          - id: prettier
            files: \.(css|less|scss|ts|tsx|graphql|gql|js|jsx|md|yml|yaml)$
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.8.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@8.8.0
                - "eslint-config-prettier@8.3.0"
                - prettier@2.5.1
    - repo: https://github.com/awebdeveloper/pre-commit-stylelint
      rev: 0.0.2
      hooks:
          - id: stylelint
            additional_dependencies:
                - prettier@2.5.1
                - stylelint@14.3.0
                - stylelint-config-recommended@6.0.0
                - stylelint-config-prettier@9.0.3
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            args: [--config=python/setup.cfg]
            additional_dependencies:
                - flake8-assertive
                - flake8-builtins
                - flake8-comprehensions
                - flake8-logging-format
                - flake8-eradicate
                - flake8-bugbear
    - repo: https://github.com/gruntwork-io/pre-commit
      rev: v0.1.17
      hooks:
          - id: shellcheck
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
          - id: blacken-docs
